# -*- coding: utf-8 -*-
"""Expense_Tracker_Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OsNztb-9io_ryGFPjjPFc2-kH5ZcVgzR

# **User Profile Setup**
"""

user_name = (input("Enter your name: "))
user_prof = (input("Enter your profession: "))

print(f"Welcome {user_name}! Let's analyze your financial health as a {user_prof}.")

"""# **Income & Expense Management**"""

user_income = float(input("Enter your monthly income: "))
user_expense = float(input("Enter your monthly expenses: "))

savings = user_income - user_expense
savings_percent = (savings / user_income) * 100

print("Total Savings:", savings)
print(f"Savings Percentage: {savings_percent:.2f}%")

"""# **Financial Health Check**"""

if savings_percent >= 20:
    print(f"Great job, {user_name}! You have a strong savings habit.")
elif savings_percent >= 10 and savings_percent < 20:
    print(f"Good, {user_name}, but you could save a bit more.")
else:
    print(f"Warning, {user_name}: Your savings are too low. Consider cutting expenses!")

"""# **Categorize Expenses**"""

essentials = float(input("How much do you spend on Essentials? "))
wants = float(input("How much do you spend on Wants? "))
sav_invest = float(input("How much do you save or invest? "))

essentials_percent = (essentials / user_income) * 100
wants_percent = (wants / user_income) * 100
sav_invest_percent = (sav_invest / user_income) * 100

print("Expense Breakdown:")
print(f"Essentials: {essentials_percent:.2f}%")
print(f"Wants: {wants_percent:.2f}%")
print(f"Savings/Investments: {sav_invest_percent:.2f}%")

"""# **Custom Goals**"""

savings_goal = float(input("What is your savings goal (in %)? "))
if savings_percent >= savings_goal:
    print(f"Congratulations, {user_name}! You’ve achieved your savings goal.")
else:
    print(f"Keep working on your savings, {user_name}. You're {savings_goal - savings_percent:.2f}% away from your goal.")

"""# **Export Summary**"""

print(f"Financial Health Summary for {user_name}")

print("Monthly Income:", user_income)
print("Monthly Expenses:", user_expense)
print(f"Total Savings: {savings} ({savings_percent:.2f}%)")
print("Expense Breakdown:")
print(f"Essentials: {essentials_percent:.2f}%")
print(f"Wants: {wants_percent:.2f}%")
print(f"Savings/Investments: {sav_invest_percent:.2f}%")
print(f"Savings Goal: {savings_goal:.2f}%")

if savings_percent >= savings_goal:
    status = "Goal Achieved!"
else:
    status = f"{savings_goal - savings_percent:.2f}% away from your goal."

print(f"Status: {status}")